- js/charts/nvd3.js
- Change mapping of data key to nvd3 default member
- Addresses issue #352
> Fix labels on interactive pie charts

- requirements.txt
Pulls in fix for persistent of the `sortable` attribute on
`summation_table` dashboard items
> Update to tessera-client 0.4.2

- js/models/dashboard-items/percentage_table.js
- templates/models/percentage_table_data.hbs
Merging from github.com:billzajac/tessera
> Add option to invert axes of percentage_table

- DEPENDENCIES.md
- Gruntfile.js
- demo/test-charts.json
- js/charts.js
- js/charts/flot.js
- js/charts/nvd3.js
- js/mixins/chart.js
- js/models/dashboard-items/stacked_area_chart.js
- requirements.txt
- templates/flot/tooltip.hbs
- tessera/static/js/flot/jquery.flot.stackpercent.js
Implements issues #364 - stacked percentage graphs in flot, and editing of stack mode for both flot and nvd3 renderers.
> Issue 364: flot stack percent

- DEPENDENCIES.md
- Gruntfile.js
- js/charts/flot.js
- js/models/dashboard-items/simple_time_series.js
- js/models/data/Summation.js
- tessera/static/css/jquery.flot.valuelabels.css
- tessera/static/js/flot/jquery.flot.js
- tessera/static/js/flot/jquery.flot.valuelabels.js
- tessera/static/tessera.css
- tessera/static/themes/tessera-dark.css
- tessera/static/themes/tessera-light.css
- tessera/static/themes/tessera-snow.css
- tessera/static/themes/tessera-solarized-dark.css
- tessera/static/themes/tessera-solarized-light.css
> Issue 362: min/max/last labels on simple time series 

- DEPENDENCIES.md
- Gruntfile.js
- js/charts/flot.js
- js/models/dashboard-items/discrete_bar_chart.js
- tessera/static/js/flot/jquery.flot.barnumbers.enhanced.js
- Added `flot.barnumbers.enhanced` plugin to display bar values
- Added toggle for the grid
A minor add-on to #160
> discrete_bar_chart enhancements

- js/models/dashboard-items/section.js
- templates/models/section.hbs
Implement issue #384, enhancing the `section` item.
> issue 384: Expand section's heading capabilities

- js/models/data/Query.js
> Issue 386: Fix transform time setting

- DEPENDENCIES.md
- Gruntfile.js
- js/charts/flot.js
- tessera/static/js/flot/jquery.flot.d3.streamgraph.js
> Issue 395: streamgraphs!

- js/charts/flot.js
- js/models/dashboard-items/bar_chart.js
> Add stream layout option to bar_chart

- js/dashboard/models/data/Summation.js
- js/dashboard/properties.js
> Issue 406: last non zero

- tessera/importer/graphite.py
Allow y-axis min, max and title to be imported from graphite dashboards. 
Tested against graphite-web 0.9.x branch
> Graphite importer enhancement

- js/charts/graphite.js
- tessera/config.py
- tessera/views.py
> Add a config setting for lineMode=connected

- js/edit/edit-mode.js
- templates/edit/dashboard_panel.hbs
- tessera/_version.py
Fixes issue #421, where queries wouldn't become editable until you added a query, deleted a query, or duplicated a query.
> Issue 421: edit queries bug

- src/ts/app/app.ts
- src/ts/app/manager.ts
Fixes and workarounds for #450
> Issue 450 mode switching bugs

- src/templates/_ds-edit-bar-definition.hbs
- src/templates/models/definition.hbs
- src/ts/app/helpers.ts
- src/ts/charts/core.ts
- src/ts/edit/edit.ts
- src/ts/index.ts
- src/ts/models/items/chart.ts
- src/ts/models/items/dashboard_definition.ts
Adds the ability to override the chart renderer setting for an entire
dashboard. Implements #460
> Issue 460 - dashboard renderer override

- src/ts/models/data/query.ts
> Add cache=true to graphite query

- src/ts/app/manager.ts
- src/ts/core/event-source.ts
- src/ts/models/dashboard.ts
- tessera/_version.py
See https://github.com/urbanairship/tessera/issues?q=milestone%3A%22Release+0.7.1%22+is%3Aclosed
> Release 0.7.1

- tessera/application.py
- tessera/helpers.py
- tessera/templates/base.html
- tessera/templates/dashboard-list.html
- tessera/templates/dashboard.html
- tessera/templates/index.html
- tessera/views.py
- tessera/views_api.py
- tessera/views_ui.py
Converts the UI and API sets of routes to flask Blueprint objects, removing the direct dependence on the app object, and wrap some of the repetitive code for the API end points in a decorator.
> Flask refactor

- requirements.txt
- tessera/_version.py
- tessera/application.py
- tessera/config.py
> Support for CORS headers on /api endpoints

- tessera-server/requirements.txt
> Bump tessera-client version

- README.md
- tessera-server/tessera/views_ui.py
Fixes issue #500, with the right target branch (`development`), this time.
> Issue 500 cookie persistence

- demo/test-charts-line-area.json
- tessera-frontend/src/css/tessera.css
- tessera-frontend/src/templates/_ds-title-bar.hbs
- tessera-frontend/src/templates/models/singlegraph.hbs
Fixes issue #505, and makes sure we have a regression test.
> Issue 505 singlegraph render error

- tessera-frontend/src/ts/models/dashboard.ts
- tessera-server/tessera/templates/import.html
- tessera-server/tessera/views_api.py
> Adding validation in the API and the import page for required title field

- tessera-frontend/src/ts/charts/flot.ts
> Flip the tooltip to the left of the cursor when it encounters the right edge of the browser

- tessera-frontend/Gruntfile.js
- tessera-frontend/package.json
> Update to typescript 1.6

- tessera-frontend/src/ts/models/items/comparison_summation_table.ts
- tessera-frontend/src/ts/models/items/percentage_table.ts
- tessera-frontend/src/ts/models/items/summation_table.ts
- tessera-frontend/src/ts/models/items/timeshift_summation_table.ts
> Don't reinitialize datatables

- tessera-frontend/src/ts/models/items/chart.ts
- tessera-frontend/src/ts/models/items/dashboard_definition.ts
- tessera-frontend/src/ts/models/items/item.ts
This should mostly, if not entirely, address #528
> Fix a DOM leak in the flot renderer

- tessera-frontend/src/ts/app/handlers/check-dirty.ts
- tessera-frontend/src/ts/app/manager.ts
- tessera-frontend/src/ts/core/property.ts
- tessera-frontend/src/ts/edit/queries.ts
- tessera-frontend/src/ts/models/dashboard.ts
- tessera-frontend/src/ts/models/items/cell.ts
- tessera-frontend/src/ts/models/items/dashboard_definition.ts
- tessera-frontend/src/ts/models/items/item.ts
> Issue 376 confirm navigation
