js/app.js, js/app/handlers/range-picker.js, tessera/templates/snippets/range-picker.html
This does two things:
* Applies the `ds.config.DISPLAY_TIMEZONE` time zone preference to the
custom range picker (addresses #354)
* Works around a change in event raising behavior in
bootstrap-timepicker that led to an infinite loop of event handlers
=> Fix for #354 (use time zone preference in range picker)

js/app/manager.js, js/models/data/Query.js
Use
[`URI.segment()`](http://medialize.github.io/URI.js/docs.html#accessors-
segment) to append URL path segments, rather than string concatenation,
avoid occasional double slashes.
=> Cleaner handling of URI paths

js/app/handlers/edit-mode.js, tessera/templates/preferences.html, tessera/templates/snippets/site-header.html, tessera/views.py
Setting the autoclose time to 0 disables auto-closing of property sheets. Implements #284
=> Issue #284: Add preference for property sheet autoclose time

Gruntfile.js, js/charts/flot.js, js/charts/nvd3.js, js/models/dashboard-items/donut_chart.js, templates/models/donut_chart.hbs, tessera/static/js/flot/jquery.flot.pie.js
Implements issue #371 - using flot for donut/pie charts when the flot renderer is selected. 
* Also adds 3 new properties to the `donut_chart` item
* 'labels' - Controls whether pie slices are labeled
* 'legend' - Controls whether the legend is visible
* 'is_pie' - If true, render a pie instead of a donut. I has a disappoint about there being no emoji for either of those.
=> Issue 371: flot pie charts

js/charts/flot.js, js/models/dashboard-items/discrete_bar_chart.js, js/models/dashboard-items/donut_chart.js
Implements #387. Filter out data series which sum to zero in donut & discrete bar charts. This makes them much more useful for queries which return many data series of which only a small number are likely to be non-zero.
=> Issue 387: Add ability to display only non-zero series in discrete charts

js/models/transform/TimeSpans.js
Include original item in the transform. This is a workaround for #329 to ensure reloading works - the original item’s query disappears otherwise. Filing a separate issue to refactor transform logic in general to clean it up.
=> Issue 329: Fix broken reload of TimeSpans transform

js/charts/graphite.js
Implements #401, for better rendering of static graphs when there are data dropouts.
=> Issue 401: Use lineMode=connected for graphite charts

js/app/manager.js, js/dashboard/models/dashboard-items/dashboard_definition.js, js/dashboard/models/dashboard-items/donut_chart.js, js/dashboard/models/data/Query.js
Fixes #410 
We were loading queries far too much when raw data is required. This change splits up the query load process.
Instead of just calling load() on all queries, `dashboard_definition.load_all()` now walks the tree to collect the queries that are actually referenced by a dashboard item, and splits them into two groups - one to load, and one to just fire (firing the loaded event is still necessary, as the `data_handler` is where chart items load their PNG from graphite when using the graphite renderer).
=> Issue 410: loading too much data

tessera/_version.py, tessera/views.py
In some deployments, we're choking on (a lack of) one of the new config parameters; `RenderContext.get_int()` shouldn't allow `None` to be passed to `int()`
=> Quick bug fix: Default to 0 in RenderContext.get_int(), not None

.gitignore
Virtualenv on some common platforms (e.g. Ubuntu + Python 2.7) will
create a local/ directory in the Virtualenv base directory; this adds
that directory to the .gitignore (the other directories that Virtualenv
creates are already ignored).
=> Add virtualenv local/ directory to .gitignore

tessera/importer/graphite.py
params is only used for querystring
data should be used for request body
alternative to #432
=> Fixed usage of POST in importer

js/dashboard/models/data/Summation.js
The defaulting of min/max to 0 wasn't being applied in all
circumstances; if there were no datapoints at all, they would remain at
`Number.MAX_VALUE` and `Number.MIN_VALUE` respectively.
I'm not convinced this fully resolves the issues here (e.g. shouldn't it
be perfectly possible for sum to be 0 _and_ for min/max to have real
values, if you have a dataset of mixed negative/positive values or just
all zeros?), but it fixes my issue at least!
=> Fix min/max calculation for empty series

js/app/handlers/dashboard-toolbar.js
When fetching the dashboard definition there's no 'dashboard' outer object,
pass the whole dashboard as it is.
=> fix view source button

js/charts/flot.js, js/charts/graphite.js, tessera/config.py, tessera/templates/snippets/site-header.html, tessera/views.py
Also renamed the GRAPHITE_CONNECTED_LINES config to just
CONNECTED_LINES, because if you want connected lines you
probably want them in all renderers.
Resolves #404.
=> Implement connected line mode for Flot charts

demo/release-notes-what-s-new-in-0-7.json, src/ts/app/manager.ts, src/ts/charts/core.ts, src/ts/charts/graphite.ts, src/ts/models/items/chart.ts, src/ts/models/items/dashboard_definition.ts, src/ts/models/items/item.ts, src/ts/models/transform/Isolate.ts
Restores the behavior of having an interactive view in ‘Isolate’, while
also allowing more flexibility in display on dashboards. Now if there’s
something you need to do with a graphite query that flot charts don’t
support, you can selectively use graphite’s PNG renderer.
Fixes #418
=> Add per-chart renderer overrides

src/ts/edit/edit.ts
The import chart from graphite URL action was out of data. Y-axis labels are no longer dropped, and yMin and yMax are supported now too. 
Fixes #455
=> Issue 455: fixing y-axis options on import from graphite URL

tessera-frontend/src/templates/flot/table_legend.hbs, tessera-frontend/src/ts/charts/flot.ts
When `hide_zero_series` is true, hide the series in the mouseover hover panel and the table legend, as well as in the chart and simple legend.
=> Issue 472: hide zero series

tessera-frontend/src/css/tessera.css, tessera-frontend/src/templates/models/summation_table.hbs, tessera-frontend/src/templates/models/summation_table_row.hbs, tessera-frontend/src/ts/charts/flot.ts, tessera-frontend/src/ts/models/items/summation_table.ts
This is a bunch of updates to `summation_table` that add two major features:
* Allows the selection of which columns are displayed
* Adds the option of a sparkline
I thought there was a long-standing issue for this, but turns out it was just an item in the TODO wiki page.
=> Sparktable

tessera-frontend/src/ts/app/manager.ts, tessera-frontend/src/ts/importer.ts, tessera-frontend/src/ts/importer/graphite.ts, tessera-frontend/src/ts/index.ts, tessera-server/tessera/templates/import.html
Implements a graphite importer in the UI, since the command line tasks will be inaccessible to most users in a typical deployment. Implements issue #512
=> Graphite importer

tessera-frontend/src/templates/action.hbs, tessera-frontend/src/templates/edit/view_query.hbs, tessera-frontend/src/ts/app/handlers/menu-presentation-actions.ts, tessera-frontend/src/ts/models/items/markdown.ts, tessera-frontend/src/ts/models/transform/Isolate.ts, tessera-frontend/src/ts/models/transform/transform.ts
Implements issue #319  - quick access to viewing the definition of the query for a specific dashboard item without going into edit mode. Also adds a view of the query to the Isolate transform.
=> Issue 319 view the query

tessera-frontend/src/ts/app/manager.ts, tessera-frontend/src/ts/charts.ts, tessera-frontend/src/ts/charts/core.ts, tessera-frontend/src/ts/charts/flot.ts, tessera-frontend/src/ts/charts/graphite.ts, tessera-frontend/src/ts/models/data/query.ts, tessera-frontend/src/ts/models/items/bar_chart.ts, tessera-frontend/src/ts/models/items/chart.ts, tessera-frontend/src/ts/models/items/dashboard_definition.ts, tessera-frontend/src/ts/models/items/discrete_bar_chart.ts, tessera-frontend/src/ts/models/items/donut_chart.ts, tessera-frontend/src/ts/models/items/simple_time_series.ts, tessera-frontend/src/ts/models/items/singlegraph.ts, tessera-frontend/src/ts/models/items/singlegraph_grid.ts, tessera-frontend/src/ts/models/items/stacked_area_chart.ts, tessera-frontend/src/ts/models/items/standard_time_series.ts, tessera-frontend/src/ts/models/items/table_presentation.ts
Second round of cleanups for #528 
- Delay obtaining DOM nodes as long as possible in chart rendering
- Cleaner cleanup() process
- Clean up chart rendering context and cached processed data
=> More memory leak tweaking

README.md
Current quick start instructions leave you with an install that will start, but throw a bunch of errors as the DB has not been initialized. The instructions on the website also need major updates, referring to a command, "inv" that does not seem to exist.
=> Fixing "quick start" instructions to include db init
